// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

//run flutter pub add firebase_core if errors occur
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPeMjvHO8FcBxYLUSS_y5Uu8NoeYc2neU',
    appId: '1:55345862060:web:36724893a96e5b62d71609',
    messagingSenderId: '55345862060',
    projectId: 'notes-app-edrick',
    authDomain: 'notes-app-edrick.firebaseapp.com',
    storageBucket: 'notes-app-edrick.appspot.com',
    measurementId: 'G-M1L44BRE5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAEsrccSDevxaPg79G8zWH8AGO4bEwDlA',
    appId: '1:55345862060:android:f3465a324cb2e868d71609',
    messagingSenderId: '55345862060',
    projectId: 'notes-app-edrick',
    storageBucket: 'notes-app-edrick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfkV1Ma_KknbCF_C8rvxx3hya8g9dVbNQ',
    appId: '1:55345862060:ios:1846f7440d818d30d71609',
    messagingSenderId: '55345862060',
    projectId: 'notes-app-edrick',
    storageBucket: 'notes-app-edrick.appspot.com',
    iosClientId:
        '55345862060-3aia4udfvh5vmg3gm03te5nmpvhttmkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourseBeginner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfkV1Ma_KknbCF_C8rvxx3hya8g9dVbNQ',
    appId: '1:55345862060:ios:1846f7440d818d30d71609',
    messagingSenderId: '55345862060',
    projectId: 'notes-app-edrick',
    storageBucket: 'notes-app-edrick.appspot.com',
    iosClientId:
        '55345862060-3aia4udfvh5vmg3gm03te5nmpvhttmkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCourseBeginner',
  );
}
